src/Entity/Projects.php
<?php

namespace App\Entity;

use App\Repository\ProjectsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjectsRepository::class)
 */
class Projects
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $language;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $conditions;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getConditions(): ?string
    {
        return $this->conditions;
    }

    public function setConditions(?string $conditions): self
    {
        $this->conditions = $conditions;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

src/Form/ProjectsType.php
<?php

namespace App\Form;

use App\Entity\Projects;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjectsType extends AbstractType
{

    const LANGUAGES = [
        'PHP' => 'PHP',
        'Javascript' => 'Javascript',
        'SASS' => 'SASS',
        'HTML' => 'HTML',
        'CSS' => 'CSS',
        'Symfony' => 'Symfony',
        'Twig' => 'Twig',
        'MVC' => 'MVC',
        'Méthode Agile' => 'Méthode Agile',
    ];

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class, [
                'attr' => ['class' => 'form-control'],
            ])
            ->add('language', ChoiceType::class, [
                'choices' => [
                    'Langages' => self::LANGUAGES
                ],
                'attr' => ['class' => 'form-control'],
                'expanded' => 'true',
            ])
            ->add('conditions', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'required' => false,



            ])
            ->add('Description', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'rows' => 6
                ],

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Projects::class,
        ]);
    }
}

src/Controller/ProjectsController.php
<?php

namespace App\Controller;

use App\Entity\Projects;
use App\Form\ProjectsType;
use App\Repository\ProjectsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/projects")
 */
class ProjectsController extends AbstractController
{
    /**
     * @Route("/", name="projects_index", methods={"GET"})
     * @param ProjectsRepository $projectsRepository
     * @return Response
     */
    public function index(ProjectsRepository $projectsRepository): Response
    {
        return $this->render('projects/index.html.twig', [
            'projects' => $projectsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="projects_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $project = new Projects();
        $form = $this->createForm(ProjectsType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($project);
            $entityManager->flush();

            return $this->redirectToRoute('projects_index');
        }

        return $this->render('projects/new.html.twig', [
            'project' => $project,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="projects_show", methods={"GET"})
     * @param Projects $project
     * @return Response
     */
    public function show(Projects $project): Response
    {
        return $this->render('projects/show.html.twig', [
            'project' => $project,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="projects_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Projects $project
     * @return Response
     */
    public function edit(Request $request, Projects $project): Response
    {
        $form = $this->createForm(ProjectsType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('projects_index');
        }

        return $this->render('projects/edit.html.twig', [
            'project' => $project,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="projects_delete", methods={"DELETE"})
     * @param Request $request
     * @param Projects $project
     * @return Response
     */
    public function delete(Request $request, Projects $project): Response
    {
        if ($this->isCsrfTokenValid('delete'.$project->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($project);
            $entityManager->flush();
        }

        return $this->redirectToRoute('projects_index');
    }
}

templates/projects/_delete_form.html.twig
<form method="post" action="{{ path('projects_delete', {'id': project.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
    <button class="btn">Effacer</button>
</form>

templates/projects/_form.html.twig
{{ form_start(form) }}
        {{ form_start(form) }}
        <div class="m-5">
            <div class="mt-5">
                {{ form_row(form.nom) }}
            </div>
            <div class="mt-5">
                {{ form_row(form.language) }}
            </div>
            <div class="mt-5">
                {{ form_row(form.conditions) }}
            </div>
            <div class="mt-5">
                {{ form_row(form.Description) }}
            </div>
            <div class="mt-5">
                <button class="btn">{{ button_label|default('Enregistrer') }}</button>
                {{ form_end(form) }}
            </div>
        </div>

templates/projects/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Damien C. | Éditer{% endblock %}

{% block body %}
    <h1>Éditer un Projet</h1>

    <div class="row">
        <div class="col-12">
            {{ include('projects/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

            <a href="{{ path('projects_index') }}">Retour à la liste des Projets</a>

            {{ include('projects/_delete_form.html.twig') }}
        </div>
    </div>

{% endblock %}

templates/projects/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Damien C. | Portfolio
{% endblock %}

{% block body %}
    {% for project in projects %}
        <main class="page-content container-fluid">
            <div class="row"></div>
            <div class="card">
                <div class="content">
                    <h2 class="title">{{ project.nom }}</h2>
                    <h4 class="">{{ project.conditions }}</h4>
                    <p class="copy">{{ project.description }}</p>
                    <a href="{{ path('projects_edit', {'id': project.id}) }}" class="btn">Modifier</a>
                </div>
            </div>
        </main>
    {% endfor %}
    <div>
        <div>
            <a class="btn btn-lg btn-outline-dark mb-5" href="{{ path('home') }}">Retour a la page d'accueil</a>
        </div>
    </div>
{% endblock %}

templates/projects/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Projects{% endblock %}

{% block body %}
    <h1 class="text-center m-5">Ajouter un nouveau projet</h1>

    {{ include('projects/_form.html.twig') }}

    <a href="{{ path('projects_index') }}">Retour aux Projets</a>
{% endblock %}

templates/projects/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projects{% endblock %}

{% block body %}
    <h1>Projects</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ project.nom }}</td>
            </tr>
            <tr>
                <th>Language</th>
                <td>{{ project.language }}</td>
            </tr>
            <tr>
                <th>Conditions</th>
                <td>{{ project.conditions }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ project.Description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('projects_index') }}">back to list</a>

    <a href="{{ path('projects_edit', {'id': project.id}) }}">edit</a>

    {{ include('projects/_delete_form.html.twig') }}
{% endblock %}